# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MyService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fMyService.proto\x12\x10org.example.grpc\" \n\tMyRequest\x12\x13\n\x0brequestText\x18\x01 \x01(\t\"\"\n\nMyResponse\x12\x14\n\x0cresponseText\x18\x01 \x01(\t2Y\n\tMyService\x12L\n\x0fprintMyResponse\x12\x1b.org.example.grpc.MyRequest\x1a\x1c.org.example.grpc.MyResponseB\x02P\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MyService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _MYREQUEST._serialized_start=37
  _MYREQUEST._serialized_end=69
  _MYRESPONSE._serialized_start=71
  _MYRESPONSE._serialized_end=105
  _MYSERVICE._serialized_start=107
  _MYSERVICE._serialized_end=196
# @@protoc_insertion_point(module_scope)
